FROM node:18-bullseye

# Install system packages for ffmpeg NPM dependency
RUN apt-get -y update \
  && apt-get -y install --no-install-recommends ffmpeg \
  && apt-get clean

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "node", "index.js" ]
